version: '3.9'

services:
  mysql_database:
    image: mysql
    environment:
      - MYSQL_DATABASE=database_test
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "4000:3306"
    volumes:
      - ./mysql_db:/data/db
    
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:9000
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_database
    environment:
      - DEV_DB_HOST=mysql_database
      - DEV_DB_PORT=3306
      - DEV_DB_USERNAME=root
      - DEV_DB_PASSWORD=admin
      - DEV_DB_NAME=database_test
      


