@HOST = http://localhost:9000/v1

### login
POST {{HOST}}/auth/sign-in
Content-Type: application/json

{
  "email":"baotrandinh.ute@gmail.com",
  "password":"hello124@"
}

### register
POST {{HOST}}/auth/sign-up
Content-Type: application/json

{
  "name":"bao tran",
  "password":"hello",
  "email":"baotrandinh100@gmail.com"
}

### active account
GET {{HOST}}/auth/active?token=375a19ea-d382-48c4-aa87-d191009e581e&userId=2

{

}

### check send email
POST {{HOST}}/auth/email-reset-password
Content-Type: application/json

{
  "email":"baotrandinh100@gmail.com"
}

### reset password
POST {{HOST}}/auth/reset
Content-Type: application/json

{
  "userId":2,
  "password":"hello123@",
  "token":"375a19ea-d382-48c4-aa87-d191009e581e"
}

### resend email
POST {{HOST}}/auth/resend
Content-Type: application/json

{
  "email":"baotrandinh.ute@gmail.com"
}